import Levenshtein
from retico_core import AbstractModule, UpdateMessage, UpdateType
from retico_core.audio import AudioIU
from retico_core.text import SpeechRecognitionIU
from retico_core.text import TextIU

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

import numpy as np

class ASRSimilarityFilterModule(AbstractModule):
    """
    A module that filters out text generated by an NLG component.
    """

    def __init__(
            self,
            max_similarity_threshold = 0.1,
            **kwargs):
        super().__init__(**kwargs)
        self._asr_buffer = ""
        self._tts_buffer = ""
        self.max_similarity_threshold = max_similarity_threshold

    @staticmethod
    def name():
        return "Robot ASR Filter Module"

    @staticmethod
    def description():
        return "A module that filters out text generated by an NLG component based on cosine similarity"

    @staticmethod
    def input_ius():
        return [SpeechRecognitionIU, TextIU]

    @staticmethod
    def output_iu():
        return SpeechRecognitionIU
    
    def process_update(self, update: UpdateMessage):
        out_um = UpdateMessage()
        has_ius = False
        for iu, ut in update:
            
            if type(iu) is TextIU:
                self._tts_buffer += self.normalize_str(iu.payload.strip())
                
            else: # assume ASR output
                # if ut == UpdateType.COMMIT:
                # #     # not sure why this was filtered out. commit messages are important upstream
                #     continue
                if iu.final:
                    print("final received")
                    self._asr_buffer = ""
                    self._tts_buffer = ""

                if ut == UpdateType.REVOKE or ut== UpdateType.COMMIT:  # TODO shouldn't we remove it???
                    # If we revoke, we should not process this IU
                    out_um.add_iu(iu, ut)
                    continue
                
                self._asr_buffer += ASRSimilarityFilterModule.normalize_str(iu.payload.strip() + ' ')
        
                similarity = ASRSimilarityFilterModule.compute_similarity(self._tts_buffer[:len(self._asr_buffer) - 1], self._asr_buffer, alpha=0.5)
                
                if similarity < self.max_similarity_threshold:
                    print("passed threshold: '" + iu.text + "' against "+self._tts_buffer)
                    out_um.add_iu(iu, ut)
                    has_ius = True
                else:
                    print(f"Filtered out ASR output due to high similarity with TTS output: '"+iu.text+"', "+self._tts_buffer)
                    
                if iu.final:
                    print("final received")
                    self._asr_buffer = ""
                    self._tts_buffer = ""
        if has_ius:
            self.append(out_um)

    @staticmethod
    def normalize_str(string):
        # Might not work for some languages as is
        return ''.join(char.lower() for char in string if (char and char.isalnum()) or char in ["'", "-", " "])

    @staticmethod
    def compute_similarity(a: str, b: str, alpha: float = 0.5) -> float:
        r"""
        Compute the hybrid similarity between two strings.
        The similarity is computed as a linear combination of cosine similarity and normalized Levenshtein distance, which is normalized to the range [0, 1]. The formula is:

        `$ similarity = \alpha * \cos(a, b) + (1 - \alpha) * \bigl(1 - \frac{\mathrm{lev}(a, b)}{\max(|a|, |b|)}\bigr) $`

        Parameters
        ----------
        a : str
            First input string.
        b : str
            Second input string.
        alpha : float
            The coefficient alpha is a float in [0, 1] that determines the weights of the cosine similarity and Levenshtein distance. The closer to 1, the more weight is given to the orthography, and the closer to 0, the more weight is given to the meaning.

        Returns
        -------
        float
            A value in [0,1] indicating combined semantic/orthographic similarity.
        """

        a = a.strip()
        b = b.strip()

        if len(a) == 0 or len(b) == 0:
            return 0.0

        # Normalized Levenshtein distance ([0, 1])
        dist = Levenshtein.distance(a, b)
        max_len = max(len(a), len(b)) or 1
        norm_lev = 1.0 - dist / max_len

        # Cosine similarity ([0, 1])
        try:
            vec = TfidfVectorizer().fit([a, b])
            tfidf = vec.transform([a, b])
            cosine = float(cosine_similarity(tfidf[0], tfidf[1])[0, 0])
        except ValueError as e: # No valid words in the input
            return 0.0

        return alpha * cosine + (1 - alpha) * norm_lev


# Determines speaking state based on the provided speech generation module. When there is non trivial energy
# in the speaker output, suppresses all AudioIUs from propagating. Otherwise they just pass through.
class AudioGatingModule(AbstractModule):

    ENERGY_KEY = "energy"
    START_TALKING_THRESH = 20  # from our energy calculation

    def __init__(
            self,
            speech_gen_module,   ## we use this module's output to determine speaking state.
            **kwargs):
        super().__init__(**kwargs)
        self._is_talking = None
        self._speech_gen_module = speech_gen_module

    @staticmethod
    def name():
        return "Simple Audio Gating Module"

    @staticmethod
    def description():
        return "A simple filter that suppresses IUs from the microphone while the speaker has output."

    @staticmethod
    def input_ius():
        return [AudioIU]

    @staticmethod
    def output_iu():
        return AudioIU

    def process_update(self, update_message):
        output_update = UpdateMessage()
        has_ius = False

        for iu, ut in update_message:

            if iu.creator == self._speech_gen_module:  # use to establish talking state
                self._update_is_talking_check( AudioGatingModule._rms_energy(iu.raw_audio, iu.sample_width) )

            else:  # all other AudioIUs
                if not self._is_talking:
                    output_iu = self.create_iu(iu)
                    output_iu.set_audio(iu.raw_audio, iu.nframes, iu.rate, iu.sample_width)
                    output_update.add_iu(output_iu, ut)
                    has_ius = True

        if has_ius:
            self.append(output_update)

    # very simple threshold that triggers a change when we cross the threshold
    def _update_is_talking_check(self, energy):
        talking = energy > self.START_TALKING_THRESH

        if talking:
            if self._is_talking is None or not self._is_talking:
                print("is speaking changed to: true")
                self._is_talking = True

        else:  #not talking
            if self._is_talking is None or self._is_talking:
                print("is speaking changed to: false")
                self._is_talking = False

    # calculates energy of waveform. primitive
    @staticmethod
    def _rms_energy(audio_bytes, sample_width_bytes):
        sample_width_bits = sample_width_bytes * 8
        samples = np.frombuffer(audio_bytes, dtype=np.dtype(f"int{sample_width_bits}"))
        return np.sqrt(np.mean(samples.astype(np.float64) ** 2))